### ISSUE TITLE
导入报错啊

### ISSUE THREAD

**Issue by ec50n9** [JoshuaRogue/FancyView#1]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [site.gemus:openingstartanimation:1.0.0] C:\Users\19783\.gradle\caches\transforms-1\files-1.1\openingstartanimation-1.0.0.aar\f1fed72fa07313f9918265cacd9e3b52\AndroidManifest.xml as the library might be using APIs not available in 15
  	Suggestion: use a compatible library with a minSdk of at most 15,
  		or increase this project's minSdk version to at least 16,
  		or use tools:overrideLibrary="site.gemus.openingstartanimation" to force usage (may lead to runtime failures)

**Comment by wongzy** [comment]
请问设置的最小版本号是多少呢，这里报错的信息是版本号过低。
