### ISSUE TITLE
java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

### ISSUE THREAD

**Issue by mty0313** [JoshuaRogue/FancyView#2]
这是怎么回事呢

**Comment by VinsentY** [comment]
Drawable 强转 BitmapDrawable  高版本不兼容

重写它的方法用这个代替获得bitmap的方法： Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.drawable.test_img);

**Comment by wongzy** [comment]
https://github.com/wongzy/FancyView/commit/d76eeb89a1cc6b55442890839b52e9e5f7179a73
